apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcs.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mcs.labels" . | nindent 4 }}
spec:
  clusterIP: None   # headless — required for StatefulSet pod DNS
  selector:
    {{- include "mcs.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
