apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.configMap.namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  clusterIP: None   # headless — required for StatefulSet pod DNS
  selector:
    app: {{ .Values.app }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
