{{- range .Values.secret }}
apiVersion: recoberger.de/v1alpha1
kind:VaultSecret
metadata:
  name: {{ .name }}
  namepsace: {{ .namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-namespace: {{ .namespace }}
    meta.helm.sh/release-name: {{ .releasename}}
spec:
  path: {{ .path }}
  type: Opaque
---
{{- end}}
  